version: '3'
services:
  react-app:
    image: react-app
    ports:
      - "80:5173"
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile

  node-app:
    image: node-app
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile
    networks:
      - backend-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/Desktop/WORKSPACE/data:/data/db
    networks:
      - backend-net
  
  nginx:
    image: nginx
    ports:
      - "8080:8080"  # Nginx의 포트 설정
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx 설정 파일 마운트
    depends_on:
      node-app:
        condition: service_healthy
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge