name: CD with Gradle
# 언제 이 파일의 내용이 실행될 것인지 정의합니다. 
# 여기서는 main 브랜치에 코드가 push 되거나 pull_request되었을 때 실행할 것을 말하고 있습니다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 코드의 내용을 이 파일을 실행하여 action을 수행하는 주체(Github Actions에서 사용하는 VM)가 읽을 수 있도록 허용합니다.
permissions:
  contents: read

# 실제 실행될 내용들을 정의합니다.
jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 최신 버전에서 script를 실행
    #secret에 저장된 내 정보
    env:
     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
  # 지정한 저장소(현재 REPO)에서 코드를 워크플로우 환경으로 가져오도록 하는 github action
     - uses: actions/checkout@v3
     #nodejs 백엔드 환경 세팅
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '14'

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.EC2_ID }}
         aws-secret-access-key: ${{ secrets.EC2_KEY }}
         aws-region: ap-northeast-2
     
     - name: Login to Docker Hub
       run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
     # Github secrets로부터 데이터를 받아서, 워크 플로우에 파일을 생성
     - name: Connect to EC2 and pull Docker image
       run: |
         ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip-address "docker-compose -f /docker-compose.yml pull"
