name: push email
on:
  #push 됐을 시 실행
  push:
    branches: [ "main" ]
  #pr
  pull_request:
    branches: [ "main" ]
  #이슈 생성시 실행
  issues:

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 최신 버전에서 script를 실행
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #nodejs 백엔드 환경 세팅
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      #발신 이메일을 깃허브에 저장해서 깃허브 환경변수로 설정하는 스텝 (이미 환경변수로 해둬서 필요없음)
#      - name: Read Receiver Email
#        id: read-file
#        run: echo "RECEIVE_USER=$(cat ./github/receive.txt)" >> $GITHUB_ENV


      #메일 보내기 위한 모듈 설치
      - name: Install nodemailer
        run: npm i nodemailer

      #push / pr 경우일 때 제목 카테고리 각각 설정
      - name: Set Subject from Commit Message
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "EMAIL_SUBJECT= [PUSH]$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "EMAIL_SUBJECT= [PR]${{github.event.pull_request.title}}" >> $GITHUB_ENV
          fi
        

      #sendEmail.js 실행
      - name: Send Email
        run: node backend/src/sendEmail.js
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECEIVE_USER: ${{ secrets.RECEIVE_USER}}
          EMAIL_SUBJECT: ${{ env.EMAIL_SUBJECT}}
  #secret에 저장된 내 정보
  #secret 변수를 환경변수로 설정해주기
